language: node_js
node_js:
  - 10
directories:
  - node_modules
env:
  - CI=true
install: npm ci
script: skip

jobs:
  include:
    - stage: test & lint
      script: npm run test
      script: npm run lint
       skip_cleanup: 'true'
       
    - stage: Github Pages release
      if: branch = master
      script: npm run build-storybook
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $github_token
        local_dir: docs
        skip_cleanup: 'true'   

    - state: Npm release
      if: tags = true
      deploy:
        provider: npm
        email: yuhanlin1105@gmail.com
        api_key: $api_key
        skip_cleanup: 'true'


          
# deploy:
#   provider: npm
#   email: yuhanlin1105@gmail.com
#   api_key: $api_key
#   on:
#     tags: true
#   skip_cleanup: 'true'
