language: node_js
node_js:
  - 10
install:
  - npm ci
script:
  - npm run test:nowatch
  - npm run lint

deploy:
  provider: npm
  email: yuhanlin1105@gmail.com
  api_key: $api_key
  on:
    branch: master
  skip_cleanup: 'true'
