language: node_js
node_js:
  - 10
env:
  - CI=true
install: npm ci
script: skip

jobs:
  include:
    - stage: test & lint
      script: npm run test
      script: npm run lint
    - stage: Github Pages release
      script: npm run build-storybook
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $github_token
        local_dir: docs
        on:
          branch: master
    - stage: Npm release
      script: npm run build-storybook
      deploy:
        provider: npm run build
        api_key: $NPM_API_KEY
        on: 
          tags: true

          
# deploy:
#   provider: npm
#   email: yuhanlin1105@gmail.com
#   api_key: $api_key
#   on:
#     tags: true
#   skip_cleanup: 'true'
