language: node_js
node_js:
  - 10
env:
  - CI=true
install:
  - npm ci
script:
  - npm run build-storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: docs
  on:
    branch: master
# deploy:
#   provider: npm
#   email: yuhanlin1105@gmail.com
#   api_key: $api_key
#   on:
#     tags: true
#   skip_cleanup: 'true'
